### ISSUE TITLE
App is Crashing

### ISSUE THREAD

**Issue by hyderabadi-coder** [brminnick/InvestmentDataSampleApp#28] opened 2020-02-24 13:56 UTC
@brminnick  When i tried this sample App is crashing in Android in  Ios i did not test. Found below error while running the App .
Java.Lang.RuntimeException
  Message=Inconsistency detected. Invalid view holder adapter positionTemplatedItemViewHolder{e8605c5 position=12 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} crc643f46942d9dd1fff9.CollectionViewRenderer{53d4fa9 VFED..... ......ID 0,0-720,1024 #3}, adapter:crc643f46942d9dd1fff9.GroupableItemsViewAdapter_2@762965c, layout:androidx.recyclerview.widget.LinearLayoutManager@ab0bc48, context:android.view.ContextThemeWrapper@4e93730

Please let me know How to resolve it. If possible please send me Xaml code how to implement in Xaml .

 Thanks.

**Comment by brminnick** [comment] 2021-06-06 22:52
Cannot reproduce. Closing.

**Closed by brminnick** 2021-06-06 22:52 UTC
